### ISSUE TITLE
delete FT Category implementation 

### ISSUE THREAD

**Issue by dawciobiel** [bycza-zagroda/track-expenses-app-backend#152]
Assignees @remkro (remix), Due date 27.03.2023
&emsp; &emsp; 
- - -
### Add content by [user story] (https://github.com/bycza-zagroda/story/issues/16)
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
- - -

#### Controller

Implement code of Financial Transaction Category controller.

- should contain an end-point,
- should contain the correct call parameters, e.g.:  [ id ],
- should return a Response Entity which proper Http Status,
- validation: `id` should be greater than `0`.

#### Service

Implement code of Financial Transaction Category service.

- The service should check whether the financial category to be deleted is currently assigned to any financial transaction. If it is, then deletion is not possible. The service should throw an exception, which will be caught by the global Exception Handler
- should contain the correct call parameters, e.g.:  [ id ],
- should not return value,
- service should verify if a category with ID exists in storage and then delete this category,
- validation: `id` should be greater than `0`.

If a Financial Transaction Category is assigned to a Financial Transaction, it cannot be deleted. Information about such a fact should be returned to the front end using the appropriate Error Code.

#### DTO

No need because should be already implemented.

#### Entity

Should be implemented if doesn't exist.

#### Tests

Unit tests should be implemented.

**Comment by purbanski-deftcode** [comment]
@dawciobiel you are missing requirement for business logic to check if category is assigned to any transaction -> if it is the request should result in proper error that frontend can check and display message that category can't be deleted because of that

**Comment by dawciobiel** [comment]
@F1iper 
Please hold off on implementing this issue. The description will be changed.
