### ISSUE TITLE
bugfix/Endpoint for transactions for non-existing wallet returning empty list instead error

### ISSUE THREAD

**Issue by purbanski-deftcode** [bycza-zagroda/track-expenses-app-backend#163]
**URL**: GET https://tea-zagrodnicy.koyeb.app/api/transactions?walletId=10

In my case wallet with id 10 was already deleted. After trying to get transactions for it it is returning empty list. In that case it should return 404 as such wallet does not exists anymore.

**Comment by krzysiek578** [comment]
https://github.com/bycza-zagroda/track-expenses-app-backend/pull/168

**Comment by dawciobiel** [comment]
> #168

168? So what? So I have to guess that the content "168" means that "under link #168 there is a pull request for issue 163 <https://github.com/bycza-zagroda/track-expenses-app-backend/issues/163>"
True?

Maybe it would be worth writing one sentence for posterity?
Assuming that in fact PR-168 is to issue-163, why does PR have a completely different title than issue?

Another point: Where in the issue does it say who implements this particular issue?
