### ISSUE TITLE
bugfix/Date is nullable for transactions when it shouldn't

### ISSUE THREAD

**Issue by purbanski-deftcode** [bycza-zagroda/track-expenses-app-backend#165]
@MackowiakPiotr / 22.04.2023

**CURL**:
```
curl --request POST \
  --url https://tea-zagrodnicy.koyeb.app/api/transactions \
  --header 'Content-Type: application/json' \
  --data '{
  "walletId": 3,
  "amount": 12,
  "date": null,
  "type": "INCOME",
  "description": ""
}'
```

**NOTE**: For PATCH request date is also not validated. Also from what I saw there is date time format validation for PATCH but no such thing for POST request.

**Comment by krzysiek578** [comment]
https://github.com/bycza-zagroda/track-expenses-app-backend/pull/170
