### ISSUE TITLE
Delete method in WalletController should return Void type.

### ISSUE THREAD

**Issue by mirekgab** [bycza-zagroda/track-expenses-app-backend#166]
- - -

Delete method in Wallet Controller should return ResponseEntity\<Void\> type instead of ResponseEntity\<WalletDTO\>.

- - -

**Assignees**

- @Krzysiek

**Due date**

- 26.02.2023

**Comment by krzysiek578** [comment]
https://github.com/bycza-zagroda/track-expenses-app-backend/pull/167
