### ISSUE TITLE
Domain structure of money wallet 

### ISSUE THREAD

**Issue by MateuszBednarczyk** [bycza-zagroda/track-expenses-app-backend#22]
# Create structure:
- Empty controller implementation,
- Service interface without method declarations,
- Empty service implementation,
- The repository inheriting from the `JpaRepository` class,
- Wallet DTO.

# Implementation
- Implementation of Wallet entity.

# The wallet entity should contain:
- Id,
- wallet name,
- wallet creation date.

# Wallet name:
- cannot be empty or null,
- the maximum length of the name is 20 characters.

# Create tests
For each element (e.g. controller, service) that requires a test.

# Assignees
- @DawidStuzynski (DawidS)
- @mirekgab (Mirek Garbuś)
- @Iwona007 (Iwona)

**Comment by jkbkupczyk** [comment]
For each element (e.g. controller, service) that requires a test, ~~create an empty test framework that always passes.~~ - remove that part
