### ISSUE TITLE
bugfix/creating financial trasnaction

### ISSUE THREAD

**Issue by Iwona007** [bycza-zagroda/track-expenses-app-backend#225]
User story: bycza-zagroda/story#17

In the class FinancialTransactionServiceImpl in the method: createFinancialTransaction, if financialTransactionCreateDTO.categoryId() is not null add comparisons:
FinancialTransactionCategory.getType()==financialTransactionCreateDTO.type().

We can save entity when:
- financialTransactionCreateDTO.categoryId() == null
- financialTransactionCreateDTO.categoryId() !=null and both types are equals

If financialTransactionCreateDTO.categoryId()!=null and both types are not equals please throw error. 

This task requires the creation of unit and integration tests.

**Comment by zetxdev** [comment]
Biore
