### ISSUE TITLE
Task create Financial Transaction Category

### ISSUE THREAD

**Issue by dawciobiel** [bycza-zagroda/track-expenses-app-backend#285]
implementing: @dawciobiel 
Due date: ASAP

- - -
### TODO: 

**Part 1**
- remove userId field from FinancialTransactionCategoryCreateDTO,
- in FinancialTransactionCategoryServiceImpl correct createFinancialTransactionCategory according to changes in FinancialTransactionCategoryCreateDTO,
- correct FinancialTransactionCategoryServiceImplTest according to changes in FinancialTransactionCategoryCreateDTO

**Part 2**
- remove userId field from FinancialTransactionCategoryUpdateDTO,
- in FinancialTransactionCategoryServiceImpl correct updateFinancialTransactionCategory according to changes in FinancialTransactionCategoryUpdateDTO,
- correct FinancialTransactionCategoryServiceImplTest according to changes in FinancialTransactionCategoryUpdateDTO

### Blocker for
- #264 by @odzio33

**Comment by sylvvester** [comment]
@poneciak57 suggested using the @Size annotation instead of using `@Pattern` for validation. Check this out: https://github.com/bycza-zagroda/track-expenses-app-backend/pull/280#discussion_r1284029769
