### ISSUE TITLE
1 Discord Link Bug

### ISSUE THREAD

**Issue by wojciechwelfle** [bycza-zagroda/track-expenses-app-backend#54]
Discord invitation does not work. 
TODO: change the temporary link to the pernament link.

link to the bug:
https://github.com/bycza-zagroda/track-expenses-app-backend#readme

![discord_bug1](https://user-images.githubusercontent.com/111795716/193478661-af74c421-0bae-4ff1-b47e-2eb957e6e158.jpg)
![discord_bug2](https://user-images.githubusercontent.com/111795716/193478679-21de0a3f-d2c8-4a65-959f-13bb6048a9b9.jpg)
Also upgrade the application version from 0.2.0 to 0.2.1

**Comment by Iwona007** [comment]
Assigned @wojciechwelfle
