### ISSUE TITLE
Do a refactoring of the tests and exceptions

### ISSUE THREAD

**Issue by dawciobiel** [bycza-zagroda/track-expenses-app-backend#80]
Do a refactoring of the tests:
- WalletControllerTest
- WalletServiceTest

`WalletControllerTest` and `WalletServiceTest` can be divided into logical parts.

Do refactoring of exceptions architecture.

**Assignees:**
- @odzio33 
- @dawciobiel 

**ETA:**
18.12.2022

**Comment by Iwona007** [comment]
This is finished and merged to develop on 18.12.2022
